@startuml
'' Architecture
skinparam backgroundColor transparent
skinparam monochrome true
skinparam shadowing false

actor Player

frame Hardware {
	component Controller
	component Monitor
}

frame RaiderRoad {
	package Unity {
		component Renderer
		component Rewired <<External Plugin>>
	}
	package GameObjects {
		component Events
		component VehicleFactory
		component PlayerController{
			rectangle Drive
			rectangle Steal
		}
		component PlayerPlacement{
			component Build
			rectangle Fight
		}
		rectangle RV
		component EnemyAI{
			component Raiders
			component Vehicles
		}
	}
}

Player --> Controller : Input
Player <-- Monitor : Visual

Controller --> Rewired
Monitor <-- Renderer

Events -> VehicleFactory
VehicleFactory --> Vehicles : Builds
Renderer <-- GameObjects
Rewired --> PlayerController
PlayerController --> PlayerPlacement
Raiders <-> Vehicles : Radio

Drive --> RV

@enduml